---
# tasks file for project.server

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: 
    name:
      - apache2
      - php5-mysql
      - php5
      - libapache2-mod-php5
      - php5-mcrypt
    state: present
    