---
# tasks file for project.mysql
      # MySQL
- name: Install MySQL
  apt: 
    name:
      - mysql-server-5.6
      - python-mysqldb 
    state: present

- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass # Guarda el valor de command en una variable

# If /root/.my.cnf doesn't exist and the command is run
- debug: msg="New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed

# If /root/.my.cnf exists and the command is not run
- debug: msg="No change to root password"
  when: not mysql_new_root_pass.changed

- name: Remove anonymous users
  mysql_user: name="" state=absent
  when: mysql_new_root_pass.changed

- name: Remove test database
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed

- name: Update root password
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
  with_items:
    - "{{ansible_hostname}}"
  when: mysql_new_root_pass.changed

- name: Create my.cnf
  template: src=my.cnf dest=/root/.my.cnf
  when: mysql_new_root_pass.changed
